# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Release a beta on TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key: ENV['APP_STORE_CONNECT_API_KEY_KEY'],
      in_house: ENV['APP_STORE_CONNECT_API_KEY_IN_HOUSE']
    )
    increment_build_number
    match(type: "appstore")
    build_mac_app
    upload_to_testflight
  end
end
