name: zenbreak # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: "Your desktop oasis from screen fatigue. Reclaim your focus and well-being." # 79 char long summary
description: |
  ZenBreak is a status bar app that simply reminds you to take a break from the screen.
  It offers customisable behaviour and appearance to suit everyone needs!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


# TODO
parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
