name: Release macOS

on: [workflow_dispatch]

jobs:
  build-app:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'release'