name: Release Windows and Linux

on: [workflow_dispatch]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build jar
        run: ./gradlew jar

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v11.4
        env:
          OAUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        with:
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1